### ISSUE TITLE
Build fail when installing with opam

### ISSUE THREAD

**Issue by VictorEgret** [savonet/ocaml-ssl#82] opened 2022-04-13 15:05 UTC
Windows 10 x64, Cygwin error while installing -> dune build fail
let me know if you need more informations
![image](https://user-images.githubusercontent.com/47831936/163210855-8f20f258-6cfd-45de-baa6-ea47c094645b.png)

**Comment by Chimrod** [comment] 2022-05-22 09:46
Hello,

I also have the issue. The screenshot only show the last message (which are all warnings), but you can see the real cause in the log

```ssl_stubs.c: In function ‘ocaml_ssl_version’:
ssl_stubs.c:880:10: error: ‘TLS1_3_VERSION’ undeclared (first use in this function); did you mean ‘TLS1_2_VERSION’?
  880 |     case TLS1_3_VERSION:
      |          ^~~~~~~~~~~~~~
      |          TLS1_2_VERSION
```
[error.log](https://github.com/savonet/ocaml-ssl/files/8749156/error.log)

I do not know if this comes from an outdated package in the cygwin distribution, or a missing guard in the C stub.

**Comment by VictorEgret** [comment] 2022-05-22 11:48
> Hello,
> 
> I also have the issue. The screenshot only show the last message (which are all warnings), but you can see the real cause in the log
> 
> ```
> ssl_stubs.c:880:10: error: ‘TLS1_3_VERSION’ undeclared (first use in this function); did you mean ‘TLS1_2_VERSION’?
>   880 |     case TLS1_3_VERSION:
>       |          ^~~~~~~~~~~~~~
>       |          TLS1_2_VERSION
> ```
> 
> [error.log](https://github.com/savonet/ocaml-ssl/files/8749156/error.log)
> 
> I do not know if this comes from an outdated package in the cygwin distribution, or a missing guard in the C stub.

I just ran it again and what you see on my screenshot is the entire ERROR I get, I don't see anything like on your screenshot on my terminal.

**Comment by Chimrod** [comment] 2022-05-22 18:56
This seems to be a duplicate of #70. This issue seems to be still present in v0.5.10.

**Comment by Chimrod** [comment] 2022-05-22 21:02
I’m not sure we should close this ticket : the issue #70 is already closed and the problem is still here.

note: I’m not a maintainer in the library, and I just try to analysis and understand the issue, I didn’t said in my previous message that we problem is resolved, I just wanted to point that the issue where already reported and *considered as closed* in november 2021. However, we are two user to still have the same problem today!

**Comment by Chimrod** [comment] 2022-05-24 08:52
Hello,

I’ve manually patched ssl_stubs.cs as described in the pull request #73. The error is gone, and the compilation works.

But, it fails a step later, in the link stage, and this is caused by the cygwin environment: at the date of the comment, the package for [mingw-openssl](https://cygwin.com/cygwin/packages/summary/mingw64-x86_64-openssl.html) is still in 1.0 version, where the library [libssl-devel](https://cygwin.com/cygwin/packages/summary/libssl-devel.html) used in the compilation is in 1.1.

Conclusion: this issue is legit, and there is a missing commit in the latest package available in opam. But solving this issue will not help to install the package in cywing, as we have another issue, but which is not related with ocaml-ssl.

**Comment by anmonteiro** [comment] 2022-07-24 08:58
Does 0.5.11 work for you?

**Comment by Chimrod** [comment] 2022-07-24 17:51
Thanks, the last update was installed correctly!

```
<><> Processing actions ><><><><><><><><><><><><><><><><><><><><><>
∗ installed conf-libssl.4
∗ installed ssl.0.5.11
Done.
```

**Closed** 2022-07-25 00:57 UTC
